# Generated by Django 5.0.1 on 2024-02-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
