# Generated by Django 5.0.1 on 2024-02-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_favourite_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_imagee',
        ),
    ]
