# Generated by Django 5.0.1 on 2024-02-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_product_image_product_product_imagee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_imagee',
            new_name='product_image',
        ),
    ]
